### ISSUE TITLE
Harnessing 2024

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/umatt-general#1]
# [001] Harnessing 2024
**Lead:** Shannon
**Cost:** Minimal (less than $50.00)
**Time:** May 2024

## Overview
> **Motivation:** _We need harnessing for our 2024 tractor, early enough that we can test it and get it properly routed. Additionally, we need it to be well documented and thought out so we don't repeat the mistakes of last year (i.e. building it from scratch at competition)._

We need to document last year's harnessing, or what what's left of it. With this, we need to plan out harnessing for 2024. This includes fixing last years issues and adding in the sensors, interlocks, etc... we didn't have time for last year. Once planned, we need to build, test, and install harnessing on this year's tractor. This will likely involve coordinating with mechanicals for routing. In addition, we should create a document of electrical drawing standards and create an introduction to AutoCAD new-members tutorial.

## Timeline
1. **December 2023:** Document last year's harnessing.
2. **January 2024:** Add new revisions and changes for 2024.
3. **April 2024:** Physical harnessing built and tested.
4. **May 2024:** Route harnessing on tractor.

## Functional Requirements
- Harnessing should minimally connect all essential drivetrain and operator components.
- Harnessing should be properly routed to avoid unnecessary wear.

## Task
- [ ] Document last year's harnessing
- [ ] New revisions and changes for 2024
- [ ] Build physical harnessing (and testing)
- [ ] Coordinate with mechanical about harness routing
