### ISSUE TITLE
PID Controller

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/umatt-general#10]
# [010] PID Controller
**Lead:** Unassigned
**Cost:** ?
**Timeline:** May 2025

## Overview
> **Motivation:** If we control the engine throttle correctly, we can maintain the RPM speed that provides maximum torque. This would greatly improve our performance in the tractor pull and simplify the operators job.

## Tasks
- [ ] Install RPM sensor
- [ ] Implement electric throttle control
- [ ] Connect PID controller
