### ISSUE TITLE
Display Controller

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/umatt-general#13]
# [013] Display Controller
**Lead:** Unassigned
**Cost:** $200
**Timeline:** May 2024

## Overview
> **Motivation:** We want abstract our display control onto a different controller than the drivetrain so that we can maintain the benefits of a microcontroller system. We also want to add flexibility and functionality to our tractor display, improving diagnostics and control.

We want to make the tractor display it's own isolated system, designed to run on a Raspberry Pi. Ideally this will be on it's own enclosed controller unit to improve durability and safety. In addition, we want to add functionality to the display, including:

- Wireless connection to a tablet (via Wi-Fi).
- Improved UI design.
- Functionality added for diagnostics & control (the stuff we didn't get to last year.

## Cost

| Expense Description    | Cost     |
|-------------------------------|------------|
| Raspberry Pi                | $40.00 |
| CAN chip                     | $20.00 |
| PCB mount                  | ?          |
| PCB headers               | $60.00 |
| PCB enclosure            | $30.00 |

## Functional Requirements
- 

## Tasks
- [ ] Port code over to a new project
- [ ] Design PCB and physical enclosure
- [ ] Improve UI
- [ ] Add diagnostic & control functionality
