### ISSUE TITLE
Drivetrain Test Bench

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/umatt-general#2]
# [002] Drivetrain Test Bench
**Lead:** Kameron
**Cost:** $600
**Time:** January 2024

## Overview
> **Motivation:** Once mechanical projects have been designed and are ready to be manufactured (typically late Fall), the tractor will have to be disassembled in order to rebuild it for the following competition year. During this period, electrical projects are unable to be tested as they often require a functional drivetrain.

To address this problem, the following proposed design will _simulate_ a tractor drivetrain so that electrical systems can be tested without a running tractor. As such, the main objective of the drivetrain test bench is: _functionally operate as closely to a real drivetrain as possible_.

The proposed design for the drivetrain test bench is to mount drivetrain components on an industrial-grade shelving unit. Powered by an engine from previous competition years, the test bench will use an electric generator and Sevcon motor controller to drive the output of an electric motor. RPM sensors will monitor the speed and direction of both the driveshaft and electric motor output, displaying this information to the operator. Physical toggle switches and throttles will allow the operator to control the engine, and Sevcon manually. In addition, the system will allow for an Ardunio micro-controller to plug in and take control of the Sevcon's operation.

## Cost
The table below outlines the major components required to build the test bench. While unforeseen costs may arise, a buffer of $120 has been included in the cost analysis. Fortunately, a number of the most expensive components can be reused from off the tractor. This has two major benefits:

1. We greatly reduce the overall cost of the system.
2. It provides us the opportunity to strain/durability test the equipment we will be installing on the tractor.

Unfortunately this also means that if something goes wrong with the test bench, it could cause serious set-backs to the production of a competition tractor. These factors should be kept in mind when determining which components should be reused/purchased.

| Component                                        | Cost      | Can Reuse |
|--------------------------------------------------|-----------|-----------|
| Sevcon Gen4 Motor Controller (Size 6)            | $2,021.00 | yes       |
| Motenergy ME1302 (DLC-28) Brushless PMAC Motor   | $1,495.00 | yes       |
| Motenergy ME1909 (ME1003) Brush-type PMDC Motor  | $850.00   | yes       |
| 12V Battery                                      | ~ $150.00 | no        |
| LEV200A4NAF DC Contactor                         | $100.00   | yes       |
| Direction/Speed Sensor (x2)                      | $10.00    | ?         |
| Arduino Nano Every with Headers                  | $14.70    | no        |
| HD44780 1602 LCD Display Module                  | $8.99     | no        |
| Heavy Duty Industrial Welded Steel Shelving Unit  | $248.00   | no        |
| Jerry Can (25L)                                  | $24.76    | maybe     |
| Miscellaneous electrical components & wiring    | ~ $60.00  | mostly    |
| Miscellaneous steel and hardware for mounting    | ~ $80.00  | some      |

To build a drivetrain test bench with all new equipment would require a whopping total of around **$5,000.00**. However, taking into account the recommended components which can be re-purposed from our competition tractor, the estimated cost to build the test bench drops to approximately **$600.00**.

## Timeline
The timeline for building this test bench will need to be quite fast as we would like to have it in place for testing once mechanicals are ready to dis-assemble our previous year's tractor. This puts our deadline for a working unit at around the end of Fall term 2023.

1. **October 2023:** Harnessing designs finalized.
2. **November 2023:** Mechanical designs finalized. Required material and parts ordered.
3. **December 2023** Code for the drivetrain controller completed.
4. **January 2024** Test bench unit built and ready for testing.

## Functional Requirements
In order to be both beneficial and feasible to the team, the design must adhere to the following:

- Functionally _mock_ the operation of an actual drivetrain system (without the transmission). A drivetrain controller designed for the tractor should be able to plug into this unit without modification.
- Provide data feed-back to the operator on the state of the simulated "drivetrain" that is both beneficial for testing and optimization.
- Should be easy to assemble and dis-assemble, allowing for future modifications and quick removal of components shared with the tractor.
- Provide these functions at a fraction of the cost of building a new tractor. Should be under a quarter the cost of building a tractor from scratch.

## Tasks
- [ ] Design harnessing for the test bench.
- [ ] Coordinate with mechanical on design and purchase of materials.
- [ ] Write code for the test bench inputs/sensors.
- [ ] Assemble and test unit.
