### ISSUE TITLE
Control/Relay Board Improvements

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/umatt-general#4]
# [004] Control/Relay Board Improvements 2024
**Lead:** Unassigned
**Cost:** $200
**Timeline:** May 2025

## Overview
> **Motivation:** If something happens to either PCBs, we currently don't have any back-ups. That said, the existing control/relay boards are undocumented and built with the 2020 capstone project in mind. In order for software to move in new directions, design changes to the PCBs are needed. Additionally, to improve the quality and manufacturability of our boards, we should simplify, ruggedize, and streamline production of our boards.

This is a huge undertaking, and will likely require a lot of learning, experimenting, and time. So in order to simplify things I propose to break up this project into 2 parts:

1. Document and built backup PCBs for the 2024 competition year.
2. Begin design on PCB improvements which we will plan to be executed for the 2025 competition year.

Building backups for the control/relay boards should be a fairly straight-forward task. It will give us a chance to document the current boards, gain a better understanding of them, and learn the production process of PCBs.

Once backups have been made for bother boards, design can begin on their next iterations. In particular, the features I would like to add for 2025 include:

- Separate the control board into a **I/O Board** and **Power Board** (which could optionally include the relay board functionality).
- Generalize the interface of the I/O Board to include **CAN Bus** and be more compatible different controller, sensor, and output configurations.
- Make the boards more compact by moving to surface mounted components.
- Ruggedize the boards by housing them in proper controller encasing.

## Cost
The costs of building PCBs is largely unknown to me. My current estimate is $200, but I have no real idea of whether that is a reasonable figure. A big part of this project would be outlining the process of building custom PCBs, which would necessarily include a large section on the various costs.

## Timeline
1. **October 2023** Document current control/relay boards.
2. **November 2023:** Order PCB components for the backup boards.
3. **January 2024:** Built and test the backup PCBs.
4. **February 2024:** Begin design work on 2025 PCB improvements.
5. **April 2025:** Determine a more detailed plan for PCB design in 2024-2025.

## Functional Requirements
- The backup boards should functionally operate exactly as the existing boards operate.
- The process of ordering and assembling PCBs should be well documented. Including general steps, costs, and links to components/manufactures.

## Tasks
- [ ] Document current PCB boards.
- [ ] Order PCB and components for backup boards.
- [ ] Build and test the backup boards.
- [ ] Determine a design plan for the 2025 boards.
